'use client';

import { useSession, signOut } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { jsPDF } from 'jspdf';

export default function DashboardPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [mounted, setMounted] = useState(false);
  const [loading, setLoading] = useState(true);
  const [dashboardData, setDashboardData] = useState(null);

  useEffect(() => {
    setMounted(true);
    if (status === 'unauthenticated') router.push('/login');
  }, [status, router]);

  useEffect(() => {
    if (mounted && status === 'authenticated') {
      fetchDashboardData();
    }
  }, [mounted, status]);

  const fetchDashboardData = async () => {
    try {
      const response = await fetch('/api/dashboard/stats');
      const json = await response.json();
      
      if (json.success) {
        setDashboardData(json.data);
      }
    } catch (error) {
      console.error('Failed to fetch dashboard data:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleExportPDF = async () => {
    try {
      // Fetch comprehensive data for PDF
      const response = await fetch('/api/dashboard/export-pdf');
      const json = await response.json();
      
      if (!json.success) {
        alert('Failed to fetch data for PDF');
        return;
      }

      const data = json.data;
      
      // Create PDF
      const doc = new jsPDF();
      let yPos = 20;
      
      // Header
      doc.setFontSize(24);
      doc.setTextColor(75, 85, 99);
      doc.text('Dashboard Report', 20, yPos);
      
      yPos += 10;
      doc.setFontSize(10);
      doc.setTextColor(107, 114, 128);
      doc.text(`Generated: ${new Date(data.generatedDate).toLocaleString()}`, 20, yPos);
      doc.text(`Generated By: ${data.generatedBy}`, 20, yPos + 5);
      
      yPos += 15;
      
      // Stats Overview
      doc.setFontSize(16);
      doc.setTextColor(75, 85, 99);
      doc.text('Key Statistics', 20, yPos);
      
      yPos += 10;
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
      
      const stats = [
        { label: 'Total Revenue', value: `BDT ${data.stats.totalRevenue.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, change: `${data.stats.revenueChange >= 0 ? '+' : ''}${data.stats.revenueChange}%` },
        { label: 'Total Orders', value: data.stats.totalOrders.toLocaleString('en-US'), change: `${data.stats.ordersChange >= 0 ? '+' : ''}${data.stats.ordersChange}%` },
        { label: 'Total Customers', value: data.stats.totalCustomers.toLocaleString('en-US'), change: '' },
        { label: 'Conversion Rate', value: `${data.stats.conversionRate}%`, change: '' },
        { label: 'Active Products', value: `${data.stats.activeProducts} of ${data.stats.totalProducts}`, change: '' },
        { label: 'Avg Order Value', value: `BDT ${data.stats.avgOrderValue.toFixed(2)}`, change: '' },
        { label: 'Pending Orders', value: data.stats.pendingOrders.toLocaleString('en-US'), change: '' },
        { label: 'Completed Orders', value: data.stats.completedOrders.toLocaleString('en-US'), change: '' },
        { label: 'Cancelled Orders', value: data.stats.cancelledOrders.toLocaleString('en-US'), change: '' },
        { label: 'Out of Stock', value: data.stats.outOfStock.toLocaleString('en-US'), change: '' },
        { label: 'Low Stock', value: data.stats.lowStock.toLocaleString('en-US'), change: '' },
      ];
      
      stats.forEach((stat, index) => {
        if (yPos > 250) {
          doc.addPage();
          yPos = 20;
        }
        
        doc.text(`${stat.label}:`, 25, yPos);
        doc.setFontSize(11);
        doc.text(stat.value, 80, yPos, { align: 'right' });
        
        if (stat.change) {
          doc.setFontSize(10);
          doc.setTextColor(34, 197, 94);
          doc.text(stat.change, 140, yPos);
        }
        
        yPos += 8;
      });
      
      yPos += 5;
      
      // Recent Orders Table
      if (data.recentOrders && data.recentOrders.length > 0) {
        doc.addPage();
        yPos = 20;
        
        doc.setFontSize(16);
        doc.setTextColor(75, 85, 99);
        doc.text('Recent Orders', 20, yPos);
        
        yPos += 10;
        doc.setFontSize(9);
        doc.setTextColor(0, 0, 0);
        
        // Table header
        doc.rect(20, yPos - 5, 170, 8);
        doc.text('Order ID', 25, yPos);
        doc.text('Customer', 55, yPos);
        doc.text('Amount', 115, yPos);
        doc.text('Status', 150, yPos);
        doc.text('Date', 175, yPos);
        
        yPos += 5;
        
        // Table rows
        data.recentOrders.slice(0, 10).forEach(order => {
          if (yPos > 270) {
            doc.addPage();
            yPos = 20;
            // Redraw header
            doc.rect(20, yPos - 5, 170, 8);
            doc.setFontSize(9);
            doc.text('Order ID', 25, yPos);
            doc.text('Customer', 55, yPos);
            doc.text('Amount', 115, yPos);
            doc.text('Status', 150, yPos);
            doc.text('Date', 175, yPos);
            yPos += 5;
          }
          
          doc.text(order.id, 25, yPos);
          doc.text(order.customer.substring(0, 20), 55, yPos);
          doc.text(`BDT ${order.amount.toFixed(2)}`, 115, yPos);
          doc.text(order.status, 150, yPos);
          doc.text(order.date, 175, yPos);
          
          yPos += 7;
        });
      }
      
      // Top Products Table
      if (data.topProducts && data.topProducts.length > 0) {
        doc.addPage();
        yPos = 20;
        
        doc.setFontSize(16);
        doc.setTextColor(75, 85, 99);
        doc.text('Top Products by Sales', 20, yPos);
        
        yPos += 10;
        doc.setFontSize(9);
        doc.setTextColor(0, 0, 0);
        
        // Table header
        doc.rect(20, yPos - 5, 170, 8);
        doc.text('Product Name', 25, yPos);
        doc.text('Sales', 120, yPos);
        doc.text('Revenue', 145, yPos);
        
        yPos += 5;
        
        // Table rows
        data.topProducts.slice(0, 10).forEach((product, index) => {
          if (yPos > 270) {
            doc.addPage();
            yPos = 20;
            // Redraw header
            doc.rect(20, yPos - 5, 170, 8);
            doc.setFontSize(9);
            doc.text('Product Name', 25, yPos);
            doc.text('Sales', 120, yPos);
            doc.text('Revenue', 145, yPos);
            yPos += 5;
          }
          
          doc.text(`${index + 1}. ${product.name.substring(0, 30)}`, 25, yPos);
          doc.text(product.sales.toString(), 120, yPos);
          doc.text(`BDT ${product.revenue.toFixed(2)}`, 145, yPos);
          
          yPos += 7;
        });
      }
      
      // Footer on last page
      const pageCount = doc.internal.pages.length - 1;
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(156, 163, 175);
        doc.text('Looklify - Dashboard Report', 20, 285);
        doc.text(`Page ${i} of ${pageCount}`, 190, 285, { align: 'right' });
      }
      
      // Save PDF
      const fileName = `dashboard-report-${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);
      
    } catch (error) {
      console.error('Failed to generate PDF:', error);
      alert('Failed to generate PDF report');
    }
  };

  if (status === 'loading' || loading)
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800">
        <div className="text-center">
          <div className="h-16 w-16 border-4 border-purple-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-gray-600 dark:text-gray-400 text-lg font-medium">Loading your dashboard...</p>
        </div>
      </div>
    );

  if (!session || !mounted) return null;

  const formatCurrency = (amount) => {
    return `BDT ${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  };

  const formatNumber = (num) => {
    return num.toLocaleString('en-US');
  };

  const stats = [
    { 
      name: 'Total Revenue', 
      value: dashboardData?.stats ? formatCurrency(dashboardData.stats.totalRevenue) : 'BDT 0.00', 
      change: dashboardData?.stats ? `${dashboardData.stats.revenueChange >= 0 ? '+' : ''}${parseFloat(dashboardData.stats.revenueChange).toFixed(1)}%` : '+0%', 
      positive: !dashboardData?.stats || parseFloat(dashboardData.stats.revenueChange) >= 0,
      icon: (
        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1" />
        </svg>
      ),
      color: 'from-green-500 to-emerald-600',
      bgColor: 'bg-gradient-to-br from-green-50 to-emerald-50 dark:from-green-900/20 dark:to-emerald-900/20'
    },
    { 
      name: 'Orders', 
      value: dashboardData?.stats ? formatNumber(dashboardData.stats.totalOrders) : '0', 
      change: dashboardData?.stats ? `${dashboardData.stats.ordersChange >= 0 ? '+' : ''}${parseFloat(dashboardData.stats.ordersChange).toFixed(1)}%` : '+0%', 
      positive: !dashboardData?.stats || parseFloat(dashboardData.stats.ordersChange) >= 0,
      icon: (
        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
        </svg>
      ),
      color: 'from-blue-500 to-cyan-600',
      bgColor: 'bg-gradient-to-br from-blue-50 to-cyan-50 dark:from-blue-900/20 dark:to-cyan-900/20'
    },
    { 
      name: 'Customers', 
      value: dashboardData?.stats ? formatNumber(dashboardData.stats.totalCustomers) : '0', 
      change: '+0%', 
      positive: true,
      icon: (
        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
        </svg>
      ),
      color: 'from-purple-500 to-pink-600',
      bgColor: 'bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20'
    },
    { 
      name: 'Conversion Rate', 
      value: dashboardData?.stats ? `${dashboardData.stats.conversionRate.toFixed(2)}%` : '0%', 
      change: '+0%', 
      positive: true,
      icon: (
        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
        </svg>
      ),
      color: 'from-orange-500 to-red-600',
      bgColor: 'bg-gradient-to-br from-orange-50 to-red-50 dark:from-orange-900/20 dark:to-red-900/20'
    },
  ];

  const recentOrders = dashboardData?.recentOrders || [];
  const topProducts = dashboardData?.topProducts || [];

  const getStatusColor = (status) => {
    switch (status) {
      case 'Completed': return 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300';
      case 'Processing': return 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300';
      case 'Shipped': return 'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300';
      case 'Pending': return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300';
      default: return 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
            Dashboard Overview
          </h1>
          <p className="text-gray-600 dark:text-gray-400 mt-2 flex items-center gap-2">
            <span>Welcome back,</span>
            <span className="font-semibold text-gray-900 dark:text-gray-100">
              {session.user?.name || session.user?.email}
            </span>
            <span className="text-green-500">●</span>
            <span className="text-sm">Online</span>
          </p>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={handleExportPDF}
            className="flex items-center gap-2 px-4 py-2.5 border border-gray-300 dark:border-gray-600 rounded-xl hover:bg-gray-50 dark:hover:bg-gray-800 transition-all duration-200 text-sm font-medium text-gray-700 dark:text-gray-300"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Export Report
          </button>
          <button
            onClick={() => signOut({ callbackUrl: '/' })}
            className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-red-500 to-red-600 text-white rounded-xl hover:from-red-600 hover:to-red-700 transition-all duration-200 text-sm font-medium shadow-lg hover:shadow-red-500/25"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
            </svg>
            Sign Out
          </button>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, index) => (
          <div
            key={stat.name}
            className={`${stat.bgColor} border border-gray-200 dark:border-gray-700 rounded-2xl p-6 hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1`}
          >
            <div className="flex items-center justify-between mb-4">
              <div className={`p-3 rounded-xl bg-gradient-to-r ${stat.color} text-white shadow-lg`}>
                {stat.icon}
              </div>
              <div className={`text-sm font-medium px-2.5 py-1 rounded-full ${
                stat.positive 
                  ? 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300' 
                  : 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300'
              }`}>
                {stat.change}
              </div>
            </div>
            <h3 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-1">
              {stat.value}
            </h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm font-medium">
              {stat.name}
            </p>
          </div>
        ))}
      </div>

      {/* Charts and Tables Grid */}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        {/* Recent Orders */}
        <div className="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 p-6 shadow-sm hover:shadow-lg transition-shadow duration-300">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">Recent Orders</h2>
            <button 
              onClick={() => router.push('/dashboard/orders')}
              className="text-sm text-purple-600 hover:text-purple-700 font-medium transition-colors"
            >
              View All
            </button>
          </div>
          <div className="space-y-4">
            {recentOrders.length > 0 ? (
              recentOrders.map((order) => (
                <div key={order.id} className="flex items-center justify-between p-4 rounded-xl bg-gray-50 dark:bg-gray-700/50 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors">
                  <div className="flex items-center gap-4">
                    <div className="w-10 h-10 bg-gradient-to-r from-purple-500 to-pink-500 rounded-lg flex items-center justify-center text-white text-sm font-bold">
                      {order.id?.split('-')[1] || order.id}
                    </div>
                    <div>
                      <p className="font-semibold text-gray-900 dark:text-gray-100 text-sm">
                        {order.customer}
                      </p>
                      <p className="text-gray-500 dark:text-gray-400 text-xs">{order.date}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="font-bold text-gray-900 dark:text-gray-100 text-sm">{order.amount}</p>
                    <span className={`inline-block px-2 py-1 rounded-full text-xs font-medium ${getStatusColor(order.status)}`}>
                      {order.status}
                    </span>
                  </div>
                </div>
              ))
            ) : (
              <div className="text-center py-12">
                <p className="text-gray-500 dark:text-gray-400">No orders yet</p>
              </div>
            )}
          </div>
        </div>

        {/* Top Products */}
        <div className="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 p-6 shadow-sm hover:shadow-lg transition-shadow duration-300">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">Top Products</h2>
            <button className="text-sm text-purple-600 hover:text-purple-700 font-medium transition-colors">
              View Report
            </button>
          </div>
          <div className="space-y-4">
            {topProducts.length > 0 ? (
              topProducts.map((product, index) => (
                <div key={product.name} className="flex items-center justify-between p-4 rounded-xl bg-gray-50 dark:bg-gray-700/50 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors">
                  <div className="flex items-center gap-4">
                    <div className={`w-10 h-10 rounded-lg flex items-center justify-center text-white text-sm font-bold ${
                      index === 0 ? 'bg-gradient-to-r from-yellow-500 to-orange-500' :
                      index === 1 ? 'bg-gradient-to-r from-gray-500 to-gray-600' :
                      index === 2 ? 'bg-gradient-to-r from-orange-500 to-red-500' :
                      'bg-gradient-to-r from-blue-500 to-cyan-500'
                    }`}>
                      #{index + 1}
                    </div>
                    <div>
                      <p className="font-semibold text-gray-900 dark:text-gray-100 text-sm">
                        {product.name}
                      </p>
                      <p className="text-gray-500 dark:text-gray-400 text-xs">{product.sales} sold</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="font-bold text-gray-900 dark:text-gray-100 text-sm">{product.revenue}</p>
                    <span className="text-green-600 text-xs font-medium">{product.growth}</span>
                  </div>
                </div>
              ))
            ) : (
              <div className="text-center py-12">
                <p className="text-gray-500 dark:text-gray-400">No sales data yet</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Quick Stats Row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-gradient-to-r from-purple-500 to-pink-600 rounded-2xl p-6 text-white">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-purple-100 text-sm font-medium">Active Products</p>
              <p className="text-2xl font-bold mt-1">{dashboardData?.stats ? formatNumber(dashboardData.stats.activeProducts) : '0'}</p>
              <p className="text-purple-100 text-sm mt-2">out of {dashboardData?.stats ? formatNumber(dashboardData.stats.totalProducts) : '0'} total</p>
            </div>
            <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center">
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
              </svg>
            </div>
          </div>
        </div>

        <div className="bg-gradient-to-r from-blue-500 to-cyan-600 rounded-2xl p-6 text-white">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-blue-100 text-sm font-medium">Avg. Order Value</p>
              <p className="text-2xl font-bold mt-1">{dashboardData?.stats ? formatCurrency(dashboardData.stats.avgOrderValue) : 'BDT 0.00'}</p>
              <p className="text-blue-100 text-sm mt-2">per order</p>
            </div>
            <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center">
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
              </svg>
            </div>
          </div>
        </div>

        <div className="bg-gradient-to-r from-green-500 to-emerald-600 rounded-2xl p-6 text-white">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-green-100 text-sm font-medium">Active Customers</p>
              <p className="text-2xl font-bold mt-1">{dashboardData?.stats ? formatNumber(dashboardData.stats.totalCustomers) : '0'}</p>
              <p className="text-green-100 text-sm mt-2">total registered</p>
            </div>
            <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center">
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
              </svg>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}